---
title: "Proyecto ENCOVI"
author: "Aldo Gatica - Alyson Rosales"
date: "2025-10-11"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```
# Medida de Precio del Frijol.  

- Se hizo una selección de el producto "Frijol" de la base de datos ENCOVI 2023.

```{r}
datos <- read_excel("Frijol_ENCOVI_2023.xlsx")
names(datos)[names(datos) == "P13A07E"] <- "GASTO_TOTAL"
names(datos)[names(datos) == "P13A07A"] <- "CANTIDAD_COMPRADA"
```

- Se reemplazaron los valores 0 por NA y se imputaron los valores medios para las variables GASTO_TOTAL y CANTIDAD_COMPRADA.
- Se creó la variable PRECIO_UNITARIO dividiendo GASTO_TOTAL entre CANTIDAD_COMPRADA.

```{r}
datos$CANTIDAD_COMPRADA[datos$CANTIDAD_COMPRADA == 0] <- NA
datos <- datos[!is.na(datos$CANTIDAD_COMPRADA), ]
```

```{r}
datos$PRECIO_UNITARIO <- datos$GASTO_TOTAL / datos$CANTIDAD_COMPRADA
summary(datos$PRECIO_UNITARIO)
```



```{r}
Q1 <- quantile(datos$PRECIO_UNITARIO, 0.25, na.rm = TRUE)
Q3 <- quantile(datos$PRECIO_UNITARIO, 0.75, na.rm = TRUE)
IQR <- Q3 - Q1

limite_inferior <- Q1 - 1.5 * IQR
limite_superior <- Q3 + 1.5 * IQR

datos$PRECIO_UNITARIO[datos$PRECIO_UNITARIO < limite_inferior] <- limite_inferior
datos$PRECIO_UNITARIO[datos$PRECIO_UNITARIO > limite_superior] <- limite_superior

summary(datos$PRECIO_UNITARIO)

hist(datos$PRECIO_UNITARIO, main = "Histograma de Precio Unitario después del tratamiento de outliers", xlab = "Precio Unitario", col = "lightblue", border = "black")
qqnorm(datos$PRECIO_UNITARIO, main = "QQ-Plot de Precio Unitario después del tratamiento de outliers")
qqline(datos$PRECIO_UNITARIO, col = "red")
```


```{r}
modelo <- lm(datos$CANTIDAD_COMPRADA ~ datos$PRECIO_UNITARIO, weights = datos$FACTOR, datos)
summary(modelo)
```

## Funcion de demanda
**Q = 6.393 - 0.22226 * P**

# Medida de Ingresos

```{r}
library(readxl)
bd_ing <- read_excel("Ingreso_ENCOVI_2023.xlsx")

#Inspeccionamos la base de datos
dim(bd_ing)
str(bd_ing)
View(bd_ing)

#Ordenamos la base para tener una mejor visualización del filtro que se
#realizará a continuación.
library(dplyr)
bd_ing <- bd_ing %>%
  arrange(NO_HOGAR, CP)

#Seleccionamos únicamente al jefe del hogar para tener solo un ingreso por familia.
#El jefe del hogar aparece con el código 1 en la variable CP.
#(otra opción sería hacer una suma de los ingresos de todos los miembros de la familia).

bd_ing2 <- bd_ing[(bd_ing$CP) == 1, ]
dim(bd_ing2) #me quedan 10,964 filas
View(bd_ing2)

#Vamos a hacer el análisis únicamente con ingresos laborales. Así que vamos
#a filtrar para quedarnos únicamente con los ocupados. Eso implica descartar a los
#valores perdidos.

bd_ing2sinNA <- bd_ing2[
  !is.na(bd_ing2$P10C01), 
  ]

#Inspeccionamos
dim(bd_ing2sinNA) #me quedan 8,456 filas
summary(bd_ing2sinNA$P10C01)

###Ahora vamos a revisar las variables que se van a incluir en el agregado de ingresos.
#Salario mensual. Mediana 2,240; hay 2,988 NAs
summary(bd_ing2sinNA$P10C27) 

#Bono14. Mediana 3,000; hay 6,811 NAs
summary(bd_ing2sinNA$P10C31B)

#Aguinaldo. Mediana 3,000; hay 6,956 NAs
summary(bd_ing2sinNA$P10C32B)

#Quinceavo. Mediana 2,500; hay 8,403 NAs
summary(bd_ing2sinNA$P10C34B)

#Bono de Productividad. Mediana 1,000; hay 8,316 NAs
summary(bd_ing2sinNA$P10C38B)

#Para poder construir el agregado de ingreso, necesitamos transformar los NAs
#en las variables anteriores. A todos los NAs les vamos a imputar la mediana.

#Salario mensual
bd_ing2sinNA$salariosinNA <- ifelse(is.na(bd_ing2sinNA$P10C27), median(bd_ing2sinNA$P10C27, na.rm=TRUE), bd_ing2sinNA$P10C27)
summary(bd_ing2sinNA$salariosinNA)

#Anualizamos el salario mensual
bd_ing2sinNA$salariosinNAanual <- bd_ing2sinNA$salariosinNA*12
summary(bd_ing2sinNA$salariosinNAanual)

#Bono 14
bd_ing2sinNA$P10C31BsinNA <- ifelse(is.na(bd_ing2sinNA$P10C31B), median(bd_ing2sinNA$P10C31B, na.rm=TRUE), bd_ing2sinNA$P10C31B)
summary(bd_ing2sinNA$P10C31BsinNA)

#Aguinaldo
bd_ing2sinNA$P10C32BsinNA <- ifelse(is.na(bd_ing2sinNA$P10C32B), median(bd_ing2sinNA$P10C32B, na.rm=TRUE), bd_ing2sinNA$P10C32B)
summary(bd_ing2sinNA$P10C32BsinNA)

#Quinceavo
bd_ing2sinNA$P10C34BsinNA <- ifelse(is.na(bd_ing2sinNA$P10C34B), median(bd_ing2sinNA$P10C34B, na.rm=TRUE), bd_ing2sinNA$P10C34B)
summary(bd_ing2sinNA$P10C34BsinNA)

#Bono de Productividad
bd_ing2sinNA$P10C38BsinNA <- ifelse(is.na(bd_ing2sinNA$P10C38B), median(bd_ing2sinNA$P10C38B, na.rm=TRUE), bd_ing2sinNA$P10C38B)
summary(bd_ing2sinNA$P10C38BsinNA)

#Sumamos los ingresos salariales para obtener el agregado de ingreso de cada jefe de hogar
bd_ing2sinNA$ingreso_total <- bd_ing2sinNA$salariosinNAanual +
  bd_ing2sinNA$P10C31BsinNA + bd_ing2sinNA$P10C32BsinNA +
  bd_ing2sinNA$P10C34BsinNA + bd_ing2sinNA$P10C38BsinNA
summary (bd_ing2sinNA$ingreso_total)  

#Ahora lo transformamos en términos quincenales para que esté en la misma medida
#que el consumo.
bd_ing2sinNA$ingreso_total_quincenal <- bd_ing2sinNA$ingreso_total / 24
summary (bd_ing2sinNA$ingreso_total_quincenal)  

```







